<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Vugen" productVer="2023" os="" host="19D82BFB4AFD5B2"><DocLocation><![CDATA[D:\LoadRunnerScripts\Assessment\LR_Assessment\JPetstore_solution\JPetstore_scripts]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[JPetstore_scripts]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Service: Set Sockets Option]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER>Set socket option <STRONG><FONT COLOR=#00AF00>SSL_VERSION</FONT></STRONG> with value <STRONG><FONT COLOR=#00AF00>AUTO</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[26-02-2024 - 15:20:19]]></Time>
<TimeTick>1708941019</TimeTick>
<NodeArgs eType="General" icon="3" nRep="6" >
<Disp><![CDATA[Service: Set Sockets Option]]></Disp>
</NodeArgs>
</Step>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Url: jpetstore.aspectran.com]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[26-02-2024 - 15:20:22]]></Time>
<TimeTick>1708941022</TimeTick>
<NodeArgs eType="General" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Url: jpetstore.aspectran.com]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="26-02-2024 - 15:20:19" eTime="26-02-2024 - 15:20:22" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" status="Passed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T5" iterID="1" >
<Action rID="T6">
<AName><![CDATA[Login]]></AName>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Submit Data: signon]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[26-02-2024 - 15:20:23]]></Time>
<TimeTick>1708941023</TimeTick>
<NodeArgs eType="General" icon="6" nRep="11" status="Passed" >
<Disp><![CDATA[Submit Data: signon]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t2.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="26-02-2024 - 15:20:22" eTime="26-02-2024 - 15:20:23" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="10" status="Passed" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T8">
<AName><![CDATA[Category_selection]]></AName>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Url: DOGS]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[26-02-2024 - 15:20:23]]></Time>
<TimeTick>1708941023</TimeTick>
<NodeArgs eType="General" icon="4" nRep="14" status="Passed" >
<Disp><![CDATA[Url: DOGS]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t3.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="26-02-2024 - 15:20:23" eTime="26-02-2024 - 15:20:24" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="13" status="Passed" >
<Disp><![CDATA[Category_selection Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T10">
<AName><![CDATA[Product_selection]]></AName>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Url: K9-BD-01]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[26-02-2024 - 15:20:24]]></Time>
<TimeTick>1708941024</TimeTick>
<NodeArgs eType="General" icon="4" nRep="17" status="Passed" >
<Disp><![CDATA[Url: K9-BD-01]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t4.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="26-02-2024 - 15:20:24" eTime="26-02-2024 - 15:20:24" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="16" status="Passed" >
<Disp><![CDATA[Product_selection Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T12">
<AName><![CDATA[cart]]></AName>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Url: addItemToCart]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[26-02-2024 - 15:20:25]]></Time>
<TimeTick>1708941025</TimeTick>
<NodeArgs eType="General" icon="4" nRep="20" status="Passed" >
<Disp><![CDATA[Url: addItemToCart]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t5.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="26-02-2024 - 15:20:24" eTime="26-02-2024 - 15:20:25" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="19" status="Passed" >
<Disp><![CDATA[cart Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[checkout]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Url: newOrderForm]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[26-02-2024 - 15:20:26]]></Time>
<TimeTick>1708941026</TimeTick>
<NodeArgs eType="General" icon="4" nRep="23" status="Passed" >
<Disp><![CDATA[Url: newOrderForm]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t6.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="26-02-2024 - 15:20:25" eTime="26-02-2024 - 15:20:26" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="22" status="Passed" >
<Disp><![CDATA[checkout Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T16">
<AName><![CDATA[order]]></AName>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Submit Data: newOrder]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[26-02-2024 - 15:20:27]]></Time>
<TimeTick>1708941027</TimeTick>
<NodeArgs eType="General" icon="6" nRep="26" status="Passed" >
<Disp><![CDATA[Submit Data: newOrder]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t7.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Submit Data: submitOrder]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[26-02-2024 - 15:20:28]]></Time>
<TimeTick>1708941028</TimeTick>
<NodeArgs eType="General" icon="6" nRep="27" status="Passed" >
<Disp><![CDATA[Submit Data: submitOrder]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t8.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="26-02-2024 - 15:20:26" eTime="26-02-2024 - 15:20:28" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="25" status="Passed" >
<Disp><![CDATA[order Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="5" nRep="9" status="Passed" >
<Disp><![CDATA[JPetstore_scripts Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Action rID="T19">
<AName><![CDATA[vuser_end]]></AName>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Url: catalog]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[26-02-2024 - 15:20:28]]></Time>
<TimeTick>1708941028</TimeTick>
<NodeArgs eType="General" icon="4" nRep="31" status="Passed" >
<Disp><![CDATA[Url: catalog]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t9.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="26-02-2024 - 15:20:28" eTime="26-02-2024 - 15:20:28" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="30" status="Passed" >
<Disp><![CDATA[vuser_end Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="26-02-2024 - 15:20:19" eTime="26-02-2024 - 15:20:28" passed="9" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" status="Passed" >
<Disp><![CDATA[Test JPetstore_scripts Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>